#!/usr/bin/env python3
"""Render a deterministic Markdown reference from the public argparse parser."""

from __future__ import annotations

import argparse
import os
import sys
from contextlib import contextmanager
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from ima_note_cli.cli import build_parser  # noqa: E402

OUTPUT = ROOT / "docs" / "CLI_REFERENCE.md"


def _children(parser: argparse.ArgumentParser) -> list[tuple[str, argparse.ArgumentParser]]:
    result: list[tuple[str, argparse.ArgumentParser]] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            result.extend(sorted(action.choices.items()))
    return result


def walk_parsers(parser: argparse.ArgumentParser, path: tuple[str, ...] = ()):
    yield path, parser
    for name, child in _children(parser):
        yield from walk_parsers(child, (*path, name))


def leaf_commands(parser: argparse.ArgumentParser | None = None) -> list[str]:
    parser = parser or stable_parser()
    return ["ima " + " ".join(path) for path, current in walk_parsers(parser) if path and not _children(current)]


@contextmanager
def stable_terminal_size():
    previous = {name: os.environ.get(name) for name in ("COLUMNS", "LINES")}
    os.environ["COLUMNS"] = "80"
    os.environ["LINES"] = "24"
    try:
        yield
    finally:
        for name, value in previous.items():
            if value is None:
                os.environ.pop(name, None)
            else:
                os.environ[name] = value


def stable_parser() -> argparse.ArgumentParser:
    with stable_terminal_size():
        return build_parser()


def render() -> str:
    with stable_terminal_size():
        parser = build_parser()
        lines = [
            "# CLI reference",
            "",
            "<!-- Generated by tools/render_cli_reference.py. Do not edit manually. -->",
            "",
            "This file is generated from `ima_note_cli.cli.build_parser()` and is the complete argument reference.",
            "",
            "`note_id`/`--note-id` is canonical. `doc_id`/`--doc-id` appears only as deprecated compatibility where the parser exposes it.",
            "",
        ]
        for path, current in walk_parsers(parser):
            command = "ima" + (" " + " ".join(path) if path else "")
            level = min(2 + len(path), 6)
            lines.extend(
                [
                    f"{'#' * level} `{command}`",
                    "",
                    "```text",
                    current.format_help().rstrip(),
                    "```",
                    "",
                ]
            )
    return "\n".join(lines).replace("\r\n", "\n").rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    cli = argparse.ArgumentParser()
    cli.add_argument("--check", action="store_true")
    args = cli.parse_args(argv)
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
